### PR TITLE
fix: moved node_modules from root directory to io.branch.sdk directory

### PR DESCRIPTION
**Pull request by ethanneff**
**issue** https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/205
**jira** https://branch.atlassian.net/browse/AIS-63
**tested** complete branch deep linking experience

screen shot 2016-09-22 at 4 24 04 pm

### CODE REVIEW

**Comment by aaustin** [comment]
nice find 👍

**Comment by aaustin** [comment]
can you relabel with fix: <title>?

**Comment by ethanneff** [comment]
@aaustin can you explain "relabel with fix: ?</p>"?

**Comment by aaustin** [comment]
Please read this section of contributing.md https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/CONTRIBUTING.md#commit-messages

**Comment by ethanneff** [comment]
update PR header, update commit header, ran gulp lint, ran test-harness

**Pull request merged**
