### PR TITLE
Updated native library dependencies

### PR DESCRIPTION
**Pull request by renesansz**
Pull request changes:
* Updated Android SDK dependency
* Updated iOS SDK dependency

### CODE REVIEW

**Comment by aaustin** [comment]
Three things:
- I believe you need to change the plugin.xml here https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/plugin.xml#L80 to `io.branch.sdk.android:library:2+`
- It seems like you've copied an old iOS SDK, since those files are not present in the latest version. https://github.com/BranchMetrics/ios-branch-deep-linking/tree/master/Branch-SDK/Branch-SDK/Requests
- Can you update the .framework file as well from the iOS repository?

**Comment by renesansz** [comment]
@aaustin thanks for the assistance, I've also updated the PR, please verify if this is correct now.

**Comment by aaustin** [comment]
Sorry if the second point was not clear. Please delete:
- `BranchApplyPromoCodeRequest.h`
- `BranchApplyPromoCodeRequest.m`
- `BranchGetPromoCodeRequest.h`
- `BranchGetPromoCodeRequest.m`
- `BranchLoadActionsRequest.h`
- `BranchLoadActionsRequest.m`
- `BranchValidatePromoCodeRequest.h`
- `BranchValidatePromoCodeRequest.m`

**Comment by renesansz** [comment]
@aaustin oh, I see2. I've pushed a follow-up commit to remove them.

**Comment by aaustin** [comment]
👍

**Pull request merged**
