### PR TITLE
fix: async usage of installing npm dependencies

### PR DESCRIPTION
**Pull request by ilyakamens**
Fix https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/512

### CODE REVIEW

**Comment by sequoiaat** [comment]
@ilyakamens 

Thanks for the PR. Before merging the PR,  we were for testing the PR with the latest version and made the respective changes in the script>hooks>beforePluginInstall.js file and tried to build, run & also tried to add the plugin.
 
We are still getting errors(i.e., around 10 modules missing like xml2js, node-version-compare etc.) and we added them manually then.  Is there anything we missed in the steps  ?

thanks

**Comment by ilyakamens** [comment]
Can you send me your exact repro steps? Note the difference in the GitHub urls below.

With my change:
```
$ cordova plugin rm branch-cordova-sdk
Uninstalling branch-cordova-sdk from android
Removing "branch-cordova-sdk"

$ ls plugins | grep branch

$ cordova plugin add https://github.com/propelinc/cordova-ionic-phonegap-branch-deep-linking.git
Fetching plugin "https://github.com/propelinc/cordova-ionic-phonegap-branch-deep-linking.git" via git clone
Repository "https://github.com/propelinc/cordova-ionic-phonegap-branch-deep-linking.git" checked out to git ref "master".
Installing "branch-cordova-sdk" for android
BRANCH SDK: Installing node dependency node-version-compare
BRANCH SDK: Installing node dependency mkpath
```

Without my change:
```
$ cordova plugin rm branch-cordova-sdk
Uninstalling branch-cordova-sdk from android
Removing "branch-cordova-sdk"

$ ls plugins | grep branch

$ cordova plugin add https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking.git
Fetching plugin "https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking.git" via git clone
Repository "https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking.git" checked out to git ref "master".
Installing "branch-cordova-sdk" for android
BRANCH SDK: Installing node dependency node-version-compare
Failed to install 'branch-cordova-sdk':Error: Cannot find module 'node-version-compare'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/ilyakamens/propel/freshebt-app/plugins/branch-cordova-sdk/src/scripts/ios/enableEntitlements.js:5:19
    at Object.<anonymous> (/Users/ilyakamens/propel/freshebt-app/plugins/branch-cordova-sdk/src/scripts/ios/enableEntitlements.js:101:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
Error: Cannot find module 'node-version-compare'
```

**Comment by sequoiaat** [comment]
@ilyakamens  it was our mistake in the reproduction steps.  @aaaronlopez  please merge the PR

**Comment by aaaronlopez** [comment]
@ilyakamens thank you for your contributions, lgtm 👍

**Pull request merged**
