### PR TITLE
[FIX] Missing properties when generating branch universal link

### PR DESCRIPTION
**Pull request by renesansz**
[FIX] alias, channel, feature, and stage aren't set when creating branch universal link.

### CODE REVIEW

**Comment by malua** [comment]
looking good, altough aren't `campaign ` and `type ` still missing?  they are listed here as link parameters: [https://dev.branch.io/getting-started/configuring-links/guide/#analytics-labels](url)

**Comment by renesansz** [comment]
ahh, I see, thanks for pointing out the lists of labels.
Will push an update to the PR.

**Comment by renesansz** [comment]
@malua , Hey I've updated my PR.
Somehow I can't add `campaign` param for some reason, I've been looking through the source code and nothing was mentioned about how to add the `campaign` & `type` param for generating links.
See source codes [Link Properties](https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/util/LinkProperties.java), [Branch](https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java), and [Branch Universal Object](https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/indexing/BranchUniversalObject.java)

But I was guessing that the `type` might be the `content type` for the universal object sa I've added it.
Let me know of your thoughts about this.

**Comment by aaustin** [comment]
👍

**Pull request merged**
