### PR TITLE
Handled Crash due to empty Context

### PR DESCRIPTION
**Pull request by tushar-bidchat**
The was crashing sometime randomly when user returns to app using a link. 
This was tested for twitter and facebook. The app instance is cleared before clicking the deep link.

### CODE REVIEW

**Comment by renesansz** [comment]
Hello @tushar-bidchat ,
you should have submitted an issue for this.
`getAutoInstance` shouldn't be removed from the plugin, else Branch won't be initialized.
I'll provide a follow-up fix for this.

**Comment by tushar-bidchat** [comment]
Thanks Renemari. 

I tried adding the If condition thinking that will resolve the issue. However the issue did not get resolved till I commented the piece of code. I hope that will help you in preparing a fix.

I will make sure to submit an issue in future.

**Comment by renesansz** [comment]
@tushar-bidchat ,
no worries!
It's okay, I've submitted PR #178 . I think you're getting an empty context due to the mishandled context initialization.

Let me know if it fixes the problem 👍

**Comment by tushar-bidchat** [comment]
Renemari,

I could not test this as your changes are not in the master. How can I test it?

**Comment by renesansz** [comment]
hmm. this hasn't been merged yet, just waiting for Alex to approve my pull request.
However, you can still try to test the pr by pulling it manually, see this article: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by tushar-bidchat** [comment]
Thanks Renemari




*Tushar Vengurlekar*
Mobile Applications Delivery Head, Bidchat Inc
[image: www.bidchat.com] <http://www.bidchat.com/>
web. www.bidchat.com

**Pull request closed without merging**
